# Cloudflare Pages configuration for LifeCraft
name = "lifecraft"
compatibility_date = "2024-01-01"

# Pages-specific configuration
pages_build_output_dir = "dist"

[build]
command = "npm run build"
cwd = "/"

# Environment variables
[env.production.vars]
NODE_ENV = "production"

[env.preview.vars]  
NODE_ENV = "development" 