# Cloudflare Pages configuration for LifeCraft
name = "lifecraft"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "/"
watch_dir = "src"

[build.upload]
format = "service-worker"

# Environment variables for different environments
[env.production.vars]
NODE_ENV = "production"

[env.preview.vars]
NODE_ENV = "development" 